# Generated by Django 2.1.1 on 2018-09-03 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('profession', models.CharField(max_length=20, verbose_name='Profession')),
                ('city', models.CharField(max_length=20, verbose_name='City')),
                ('arrival', models.CharField(choices=[('1', 'Train'), ('2', 'Flight'), ('3', 'Bus'), ('4', 'Own Vehicle')], max_length=20, verbose_name='Mode of Arrival')),
                ('arrival_date', models.DateTimeField(verbose_name='Arrival Date & Time')),
                ('departure', models.CharField(choices=[('1', 'Train'), ('2', 'Flight'), ('3', 'Bus'), ('4', 'Own Vehicle')], max_length=20, verbose_name='Mode of Departure')),
                ('departure_date', models.DateTimeField(verbose_name='Departure Date & Time')),
                ('hotel', models.CharField(max_length=30, verbose_name='Name of hotel')),
                ('spouse_check', models.BooleanField(verbose_name='Is your spouse coming')),
                ('spouse', models.CharField(max_length=30, verbose_name='Name of spouse')),
                ('spouse_profession', models.CharField(max_length=20, verbose_name='Profession of spouse')),
            ],
        ),
    ]
